services:

  infra-analytics: # Spring Boot Admin
    build: ./infra-analytics
    ports:
      - "10000:10000"
    networks: [backend]
    environment:
      SPRING_PROFILES_ACTIVE: docker
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://infra-analytics:10000/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 10

  infra-discovery: # Eureka
    build: ./infra-discovery
    ports:
      - "8761:8761"
    networks: [backend]
    environment:
      SPRING_PROFILES_ACTIVE: docker
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://infra-discovery:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 10

  infra-gateway: # Spring Cloud Gateway
    build: ./infra-gateway
    ports:
      - "80:80"
    networks: [backend]
    depends_on:
      infra-discovery:
        condition: service_healthy
      infra-analytics:
        condition: service_healthy
      ms-authorization:
        condition: service_healthy
      ms-user-external-project-1:
        condition: service_healthy
      ms-user-external-project-2:
        condition: service_healthy
      ms-user-external-project-3:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      # Eureka
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://infra-discovery:8761/eureka/
      EUREKA_CLIENT_REGISTER_WITH_EUREKA: "true"
      EUREKA_CLIENT_FETCH_REGISTRY: "true"
      # SCG discovery locator
      SPRING_CLOUD_GATEWAY_DISCOVERY_LOCATOR_ENABLED: "true"
      SPRING_CLOUD_GATEWAY_DISCOVERY_LOCATOR_LOWER_CASE_SERVICE_ID: "true"
      # Spring Boot Admin
      SPRING_BOOT_ADMIN_CLIENT_URL: http://infra-analytics:10000

  ms-authorization:
    build: ./ms-authorization   # ajusta esse caminho pro diret√≥rio do teu projeto
    ports:
      - "4000:4000"
    networks: [backend]
    depends_on:
      infra-discovery:
        condition: service_healthy
      infra-analytics:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SERVER_PORT: 4000
      SPRING_APPLICATION_NAME: ms-authorization
      # JWT (mapeia api.security.token.secret)
      API_SECURITY_TOKEN_SECRET: this_is_my_super_secure_secret_key_123!
      # Eureka
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://infra-discovery:8761/eureka/
      EUREKA_CLIENT_REGISTER_WITH_EUREKA: "true"
      EUREKA_CLIENT_FETCH_REGISTRY: "true"
      # Spring Boot Admin
      SPRING_BOOT_ADMIN_CLIENT_URL: http://infra-analytics:10000
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:4000/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10

  ms-user-external-project-1:
    build: ./ms-user-external-project
    ports:
      - "3001:3001" # Expose on host port 8111, internal port 80
    networks: [backend]
    depends_on:
      infra-discovery:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SERVER_PORT: 3001
      SPRING_APPLICATION_NAME: ms-user-external-project
      # Eureka
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://infra-discovery:8761/eureka/
      EUREKA_CLIENT_REGISTER_WITH_EUREKA: "true"
      EUREKA_CLIENT_FETCH_REGISTRY: "true"
      # Spring Boot Admin
      SPRING_BOOT_ADMIN_CLIENT_URL: http://infra-analytics:10000
      API_SECURITY_TOKEN_SECRET: this_is_my_super_secure_secret_key_123!
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:3001/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10

  ms-user-external-project-2:
    build: ./ms-user-external-project
    ports:
      - "3002:3002" # Expose on host port 8111, internal port 80
    networks: [backend]
    depends_on:
      infra-discovery:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SERVER_PORT: 3002
      SPRING_APPLICATION_NAME: ms-user-external-project
      # Eureka
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://infra-discovery:8761/eureka/
      EUREKA_CLIENT_REGISTER_WITH_EUREKA: "true"
      EUREKA_CLIENT_FETCH_REGISTRY: "true"
      # Spring Boot Admin
      SPRING_BOOT_ADMIN_CLIENT_URL: http://infra-analytics:10000
      API_SECURITY_TOKEN_SECRET: this_is_my_super_secure_secret_key_123!
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:3002/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10

  ms-user-external-project-3:
    build: ./ms-user-external-project
    ports:
      - "3003:3003" # Expose on host port 8111, internal port 80
    networks: [ backend ]
    depends_on:
      infra-discovery:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SERVER_PORT: 3003
      SPRING_APPLICATION_NAME: ms-user-external-project
      # Eureka
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://infra-discovery:8761/eureka/
      EUREKA_CLIENT_REGISTER_WITH_EUREKA: "true"
      EUREKA_CLIENT_FETCH_REGISTRY: "true"
      # Spring Boot Admin
      SPRING_BOOT_ADMIN_CLIENT_URL: http://infra-analytics:10000
      API_SECURITY_TOKEN_SECRET: this_is_my_super_secure_secret_key_123!
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:3003/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10

#  postgres-for-authorization:
#    container_name: authorization-db-container
#    image: postgres:15
#    environment:
#      POSTGRES_DB: master_data
#      POSTGRES_USER: root
#      POSTGRES_PASSWORD: root
#    healthcheck:
#      test: [ "CMD-SHELL", "pg_isready -U root -d master_data" ]
#      interval: 10s
#      timeout: 5s
#      retries: 5
#    ports:
#      - "5432:5432"
#    volumes:
#      - postgres-for-authorization-volume:/var/lib/postgresql/data


networks:
  backend:
    driver: bridge