# application-default.yml
spring:
  flyway:
    enabled: true
    baseline-on-migrate: true
  boot:
    admin:
      client:
        url: http://localhost:10000
  cloud:
    inetutils: # make the host chooser prefer loopback
      preferred-networks:
        - 127.0.0.1
        - localhost
      ignored-interfaces:
        - utun.*                # VPN (macOS)
        - awdl.*                # AirDrop (macOS)
#  datasource:
#    url: jdbc:h2:mem:db_user;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate.dialect: org.hibernate.dialect.H2Dialect
#  h2:
#    console:
#      enabled: true
#      path: /h2-console

  datasource:
    url: jdbc:postgresql://localhost:5433/external_user_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health
    metadata-map:
      management.context-path: /actuator

springdoc:
  details:
    security-header: Authorization
    description: Bearer + Token JWT
    title: User External Project
    version: v1
    spring-doc-url: http://localhost:3000
  swagger-ui:
    path: /api/v1/user-external-projects/swagger-ui.html
    enabled: true
    disable-swagger-default-url: true
    url: /api/v1/user-external-projects/api-docs
  api-docs:
    path: /api/v1/user-external-projects/api-docs