spring:
  boot:
    admin:
      client:
        url: http://infra-analytics:10000
        instance:
          service-url: http://infra-discovery:8761
          management-url: http://infra-discovery:8761/actuator
          health-url: http://infra-discovery:8761/actuator/health
#eureka:
#  instance:
#    prefer-ip-address: false
#    non-secure-port: 80
